# Generated by Django 5.2 on 2025-06-05 06:46

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=200, validators=[accounts.models.validate_name, django.core.validators.MinLengthValidator(3, 'First name must be at least 2 characters long.')])),
                ('last_name', models.CharField(max_length=200, validators=[accounts.models.validate_name, django.core.validators.MinLengthValidator(4, 'Last Name should be atleast 4 letter long')])),
                ('username', models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(message='Username must contain only letters, numbers, and underscores.', regex='^[a-zA-Z0-9_]+$'), django.core.validators.MinLengthValidator(4, 'Username must be at least 4 characters long.')])),
                ('email', models.EmailField(max_length=100, unique=True, validators=[accounts.models.validate_email])),
                ('phone_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superadmin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='account_users', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='account_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
