# Generated by Django 5.2 on 2025-06-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile_model',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='user_profile_model',
            name='address_line_2',
        ),
        migrations.AddField(
            model_name='user_profile_model',
            name='pincode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_profile_model',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile_model',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile_model',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='useprofilefile/'),
        ),
        migrations.AlterField(
            model_name='user_profile_model',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
