# Generated by Django 5.2.1 on 2025-05-27 06:11

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_is_admin_alter_account_is_superadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=100, unique=True, validators=[accounts.models.validate_email]),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(max_length=200, validators=[accounts.models.validate_name, django.core.validators.MinLengthValidator(3, 'First name must be at least 2 characters long.')]),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(max_length=200, validators=[accounts.models.validate_name, django.core.validators.MinLengthValidator(4, 'Last Name should be atleast 4 letter long')]),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(message='Username must contain only letters, numbers, and underscores.', regex='^[a-zA-Z0-9_]+$'), django.core.validators.MinLengthValidator(4, 'Username must be at least 4 characters long.')]),
        ),
    ]
