# Generated by Django 5.2.1 on 2025-05-27 06:13

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_account_email_alter_account_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=100, validators=[accounts.models.validate_email]),
        ),
    ]
