# Generated by Django 5.2.1 on 2025-05-26 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_code',
            field=models.CharField(max_length=4),
        ),
    ]
