# Generated by Django 5.2 on 2025-06-23 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_user'),
        ('store', '0002_wishlist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('product', 'cart')},
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
